import React from 'react';
import { ArrowRight, MessageSquareCode } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function Hero() {
  return (
    <div className="relative pt-20 pb-16 sm:pt-32 sm:pb-24 overflow-hidden">
      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col items-center text-center">

        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 mb-8">
          <span className="flex h-2 w-2 rounded-full bg-primary"></span>
          <span className="text-sm text-gray-400">AI-Powered Learning V1.0</span>
        </div>

        <h1 className="text-5xl sm:text-7xl font-extrabold tracking-tight mb-6 bg-clip-text text-transparent bg-gradient-to-b from-white to-gray-400 neon-text">
          Antigravity
          <span className="block text-2xl sm:text-4xl mt-2 font-normal text-cyan-400 font-mono">
            Hack the Planet // Learn Security
          </span>
        </h1>

        <p className="max-w-2xl text-lg text-gray-400 mb-10">
          Personalized learning paths generated by AI. Master Red Teaming, Blue Teaming, and more with a curriculum tailored to your goals.
        </p>

        <div className="flex flex-col sm:flex-row gap-4">
          <Link to="/roadmap" className="flex items-center justify-center gap-2 bg-gradient-to-r from-primary to-secondary text-white px-8 py-3 rounded-2xl font-semibold text-lg hover:opacity-90 transition-all shadow-lg shadow-primary/20">
            Generate My Learning Path
            <ArrowRight className="h-5 w-5" />
          </Link>

          <Link to="/assistant" className="flex items-center justify-center gap-2 bg-white/5 border border-white/10 text-white px-8 py-3 rounded-2xl font-medium text-lg hover:bg-white/10 transition-all">
            <MessageSquareCode className="h-5 w-5 text-gray-400" />
            Talk to AI Assistant
          </Link>
        </div>

      </div>

      {/* Background gradients */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-[500px] bg-primary/20 blur-[120px] -z-10 rounded-full opacity-50 pointer-events-none"></div>
    </div>
  );
}
